FROM node:16.14 AS builder

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . /app

EXPOSE 3000

CMD ["npm", "run", "build"]



FROM node:16-alpine3.14

WORKDIR /app

COPY package.json /app

RUN npm install

RUN npm install serve

COPY --from=builder /app/build /app/build

EXPOSE 3000

CMD ["npx", "serve", "-s", "build"]

